language: node_js
script:
  npm test
  npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target_branch: master
  on:
    branch: develop

notifications:
  email:
    - sebastian.blazquez96@gmail.com